"""
Django settings for redabot_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import firebase_admin
from firebase_admin import credentials
from dotenv import load_dotenv
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env.local'))

SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-4f(r4xo!7(&x2_7tzt1mn@&tv#*rn1muk@v8__yiwxr^iiy*(4'
)

# SECURITY WARNING: don't run with debug turned on in production!
os.environ.get('DEBUG', 'True') == 'True'

allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', 'studyratsfrontend.vercel.app')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'redabot_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'redabot_backend.wsgi.application'


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "studyrats_db",
        "USER": "studyrats_user",
        "PASSWORD": "Stuart_DB@@2024",
        "HOST": "127.0.0.1",   # importante: usar 127.0.0.1 para forçar TCP
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            # "unix_socket": "/opt/homebrew/var/mysql/mysql.sock",  # use isto só se quiser socket
        },
    }
}

database_url = os.environ.get('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://studyratsfrontend.vercel.app"
]

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    
    )
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,studyratsfrontend.vercel.app')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
#n8n
N8N_WEBHOOK_SECRET = os.getenv('https://n8n-n8n-start.eswufe.easypanel.host/webhook-test/d3aadfb9-3482-428e-9b2f-6bab1d85c088')
#firebase
cred = credentials.Certificate(os.path.join(BASE_DIR, 'firebase-credentials.json'))
firebase_admin.initialize_app(cred)
GS_BUCKET_NAME = 'studyrats-7aafb.firebasestorage.app' 
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_DEFAULT_ACL = 'publicRead' # Permite que os ficheiros sejam lidos publicamente
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = os.path.join(BASE_DIR, 'firebase-credentials.json')
