# Generated by Django 5.2.4 on 2025-07-30 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_essaysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField()),
                ('general_comment', models.TextField()),
                ('positive_points', models.JSONField(default=list)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='api.essaysubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('feedback_text', models.TextField()),
                ('is_perfect', models.BooleanField(default=False)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='api.correction')),
            ],
        ),
    ]
