# Generated by Django 5.2.4 on 2025-07-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_correction_correctioncriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='submitted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
