# Generated by Django 5.2.4 on 2025-10-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_stuartcointransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.essaysubmission')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
